### ISSUE TITLE
Version 3.1 - 1.20.1 crashes on load on the Modrinth App

### ISSUE THREAD

**Issue by KaiKikuchi** [anviaan/CreateAndSpace#3]
Just installing it and then launching it will crash the game on load.

Version: 3.1 (Fabric 1.20.1) on the Modrinth App
Client log: https://mclo.gs/c85x7jH
Crash log: https://mclo.gs/3Joe32g

**Comment by salmonellaII** [comment]
removing dashloader solved the issue for me
